### ISSUE TITLE
BIGNUM error

### ISSUE THREAD

**Issue by jegb** [Scalextrix/SolarCoin-Raspberry-Pi-Node#4]
After make process, I get this error (several times)
`bignum.h:57:24: error: invalid use of incomplete type 'BIGNUM {aka struct bignum_st}'
 class CBigNum : public BIGNUM
`

any idea what could be wrong, I am using noobs 2.4.4 raspbian installation.

**Comment by Scalextrix** [comment]
As per the guide it's required to use Raspbian Jessie, I'm assuming NOOBS will have installed Raspbian Stretch.  Please check the version and confirm, you can do that with 

> cat /etc/os-release

If it is Stretch, I did some research and it may be the open SSL libraries, try this

> sudo apt-get install libssl-dev

> make -f makefile.unix clean

Then try make again

**Comment by Scalextrix** [comment]
I was wrong about installing libssl-dev, you will need to downgrade it (back to the Jessie version)

Remove the current version of libssl-dev ( 1.1.0f-3 )
 > sudo apt-get remove libssl-dev

Set your repository list to point to "jessie" instead of "stretch", save and exit.
> sudo nano /etc/apt/sources.list

Then do sudo apt-get update to download the packages for jessie

Then do 
> sudo apt-get install libssl-dev 

package, it should be version 1.0.1t-1

> make -f makefile.unix clean

Do the make process again and finish the installation.
When complete, type 
> sudo apt-mark hold libssl-dev 

to make the package to not upgrade in the future

Switch back your sources, by changing 'jessie' back to 'stretch' in number 2

Do a 
>sudo apt-get update 

and 

> sudo apt-get upgrade 

and make sure it doesn't try and install libssl-dev (it will say it has been kept back)

**Comment by Scalextrix** [comment]
Or install Jessie on your SD card, or wait a few weeks for the latest version of SolarCoin core that won't have these issues, and you will probably need to upgrade to anyway.

**Comment by jegb** [comment]
this part was fixed, but then another error came up:
`net.cpp:64:1: error: reference to 'array' is ambiguous
 array<int, THREAD_MAX> vnThreadsRunning;
 ^~~~~
In file included from net.h:9:0,
                 from main.h:10,
                 from db.h:8,
                 from net.cpp:7:
/usr/include/boost/array.hpp:60:11: note: candidates are: template<class T, unsigned int N> class boost::array
     class array {
           ^~~~~
In file included from /usr/include/c++/6/tuple:39:0,
                 from /usr/include/c++/6/bits/stl_map.h:63,
                 from /usr/include/c++/6/map:61,
                 from serialize.h:11,
                 from bignum.h:9,
                 from main.h:8,
                 from db.h:8,
                 from net.cpp:7:
/usr/include/c++/6/array:90:12: note:                 template<class _Tp, unsigned int _Nm> struct std::array
     struct array
            ^~~~~
makefile.unix:172: recipe for target 'obj/net.o' failed
make: *** [obj/net.o] Error 1`

 I will follow your advise and install jessie, do you have a binary to share?

**Comment by Scalextrix** [comment]
Its the first bit in the guide '1 - THIS GUIDE ONLY WORKS ON RASPBIAN JESSIE, LITE DOWNLOADS AVAILABLE FROM https://downloads.raspberrypi.org/raspbian_lite/images/ make sure and use the version dated 2017-07-05'

**Comment by jegb** [comment]
Thanks!
